### ISSUE TITLE
panic for the --read-aloud option

### ISSUE THREAD

**Issue by gongchen618** [vaaandark/dioxionary#18]
I'm using `-x -r` option to do the query, and get panic for the word `hole`.
It works well when only using the `-x` option, though.

Below are the panic messages. This bug can be reliably reproduced.
```
dioxionary -x -r hole
hole
英 / həʊl / 美 / hoʊl / 
n. 洞，坑；裂口，开口；（高尔夫球运动中的）球洞；（小动物的）洞穴；令人不舒适的地方；缺点，破绽；<非正式>困境，窘境；禁闭室，单人牢房；空缺的地方（或位置）；（两个守场员间的）空地，空隙
v. （尤指给船）钻洞，打洞；击球入洞
 【名】 （Hole）（瑞典、挪）霍勒，（英）霍尔（人名）；（Hole）（英）霍尔，（瑞典、挪）霍勒（人名）
 an opening into or through something
 an opening deliberately made in or through something
 hit the ball into the hole
 make holes in
<初中> <高中> <CET4> <CET6> <考研> 
thread 'cpal_alsa_out' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/gc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.17.1/src/decoder/symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `8`', /home/gc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpal-0.15.2/src/host/alsa/mod.rs:145:9
```

**Comment by vaaandark** [comment]
> I'm using `-x -r` option to do the query, and get panic for the word `hole`. It works well when only using the `-x` option, though.
> 
> Below are the panic messages. This bug can be reliably reproduced.
> 
> ```
> dioxionary -x -r hole
> hole
> 英 / həʊl / 美 / hoʊl / 
> n. 洞，坑；裂口，开口；（高尔夫球运动中的）球洞；（小动物的）洞穴；令人不舒适的地方；缺点，破绽；<非正式>困境，窘境；禁闭室，单人牢房；空缺的地方（或位置）；（两个守场员间的）空地，空隙
> v. （尤指给船）钻洞，打洞；击球入洞
>  【名】 （Hole）（瑞典、挪）霍勒，（英）霍尔（人名）；（Hole）（英）霍尔，（瑞典、挪）霍勒（人名）
>  an opening into or through something
>  an opening deliberately made in or through something
>  hit the ball into the hole
>  make holes in
> <初中> <高中> <CET4> <CET6> <考研> 
> thread 'cpal_alsa_out' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/gc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.17.1/src/decoder/symphonia.rs:175:22
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `-1`,
>  right: `8`', /home/gc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpal-0.15.2/src/host/alsa/mod.rs:145:9
> ```

Thanks for your feedback. This bug comes from the upstream project [rodio](https://github.com/RustAudio/rodio). See this [issue](https://github.com/RustAudio/rodio/issues/496). In this issue, the author said that the new version solves this problem, but it has not been released yet, so he proposed a workaround, which is to downgrade rodio to 1.16.0.

I tried this workaround and found that it only solved the problem of panic at the assertion, but the sound still cannot be played. I then took a look at the author's unpublished fix code for this bug, and found that I just slightly modified the rust syntax to avoid panic, and it didn't solve the problem of not being able to play.

My guess is that this problem is caused by rodio or its dependencies, they may not handle audio files correctly.
